theme: jekyll-theme-cayman

title: Sara Ichinaga
author: Sara Ichinaga
description: Math for science, innovation, and building a friendlier world :)

url: "https://sichinaga.github.io"

header_pages:
  - index.md
  - research.md
  - teaching.md
  - code.md
  - resources.md
  - shirt.md
  - story.md

social-network-links:
  email: sarami7@uw.edu
  github: sichinaga

markdown: kramdown
